/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 oddysey2021.glb -T -k -t -m
*/

import { forwardRef, useImperativeHandle, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

import glbModel from '@/assets/model/oddysey2021-transformed.glb';
import { dracoPath } from '@/constant';
// import BallHelper from '@/components/BallHelper';

type GLTFResult = GLTF & {
  nodes: {
    chassis_1: THREE.Mesh;
    chassis_1_1: THREE.Mesh;
    chassis_1_2: THREE.Mesh;
    chassis_1_3: THREE.Mesh;
    chassis_1_4: THREE.Mesh;
    chassis_1_5: THREE.Mesh;
    chassis_1_6: THREE.Mesh;
    chassis_1_7: THREE.Mesh;
    chassis_1_8: THREE.Mesh;
    chassis_1_9: THREE.Mesh;
    chassis_1_10: THREE.Mesh;
    chassis_1_11: THREE.Mesh;
    chassis_1_12: THREE.Mesh;
    chassis_1_13: THREE.Mesh;
    chassis_1_14: THREE.Mesh;
    chassis_1_15: THREE.Mesh;
    chassis_1_16: THREE.Mesh;
    chassis_1_17: THREE.Mesh;
    chassis_1_18: THREE.Mesh;
    chassis_1_19: THREE.Mesh;
    chassis_1_20: THREE.Mesh;
    bumper_r_1: THREE.Mesh;
    bumper_r_1_1: THREE.Mesh;
    bumper_r_1_2: THREE.Mesh;
    bumper_r_1_3: THREE.Mesh;
    bumper_r_1_4: THREE.Mesh;
    bumper_r_1_5: THREE.Mesh;
    bumper_f_1: THREE.Mesh;
    bumper_f_1_1: THREE.Mesh;
    bumper_f_1_2: THREE.Mesh;
    bumper_f_1_3: THREE.Mesh;
    indicator_rf_1: THREE.Mesh;
    indicator_rf_1_1: THREE.Mesh;
    indicator_lf_1: THREE.Mesh;
    indicator_lf_1_1: THREE.Mesh;
    bonnet_1: THREE.Mesh;
    bonnet_1_1: THREE.Mesh;
    bonnet_1_2: THREE.Mesh;
    bonnet_1_3: THREE.Mesh;
    boot_1: THREE.Mesh;
    boot_1_1: THREE.Mesh;
    boot_1_2: THREE.Mesh;
    boot_1_3: THREE.Mesh;
    boot_1_4: THREE.Mesh;
    boot_1_5: THREE.Mesh;
    boot_1_6: THREE.Mesh;
    boot_1_7: THREE.Mesh;
    boot_1_8: THREE.Mesh;
    reversinglight_r: THREE.Mesh;
    reversinglight_l: THREE.Mesh;
    brakelight_m_1: THREE.Mesh;
    brakelight_m_1_1: THREE.Mesh;
    taillight_r_1: THREE.Mesh;
    taillight_r_1_1: THREE.Mesh;
    taillight_r_1_2: THREE.Mesh;
    windscreen_r_1: THREE.Mesh;
    windscreen_r_1_1: THREE.Mesh;
    bodyshell_1: THREE.Mesh;
    bodyshell_1_1: THREE.Mesh;
    bodyshell_1_2: THREE.Mesh;
    bodyshell_1_3: THREE.Mesh;
    bodyshell_1_4: THREE.Mesh;
    bodyshell_1_5: THREE.Mesh;
    bodyshell_1_6: THREE.Mesh;
    bodyshell_1_7: THREE.Mesh;
    door_lf_1: THREE.Mesh;
    door_lf_1_1: THREE.Mesh;
    door_lf_1_2: THREE.Mesh;
    door_lf_1_3: THREE.Mesh;
    door_lf_1_4: THREE.Mesh;
    door_lf_1_5: THREE.Mesh;
    door_lf_1_6: THREE.Mesh;
    door_lf_1_7: THREE.Mesh;
    door_lf_1_8: THREE.Mesh;
    door_lf_1_9: THREE.Mesh;
    door_lf_1_10: THREE.Mesh;
    window_lf: THREE.Mesh;
    door_rf_1: THREE.Mesh;
    door_rf_1_1: THREE.Mesh;
    door_rf_1_2: THREE.Mesh;
    door_rf_1_3: THREE.Mesh;
    door_rf_1_4: THREE.Mesh;
    door_rf_1_5: THREE.Mesh;
    door_rf_1_6: THREE.Mesh;
    door_rf_1_7: THREE.Mesh;
    door_rf_1_8: THREE.Mesh;
    door_rf_1_9: THREE.Mesh;
    door_rf_1_10: THREE.Mesh;
    window_rf: THREE.Mesh;
    door_lr_1: THREE.Mesh;
    door_lr_1_1: THREE.Mesh;
    door_lr_1_2: THREE.Mesh;
    door_lr_1_3: THREE.Mesh;
    door_lr_1_4: THREE.Mesh;
    door_lr_1_5: THREE.Mesh;
    door_lr_1_6: THREE.Mesh;
    door_lr_1_7: THREE.Mesh;
    door_lr_1_8: THREE.Mesh;
    window_lm: THREE.Mesh;
    door_rr_1: THREE.Mesh;
    door_rr_1_1: THREE.Mesh;
    door_rr_1_2: THREE.Mesh;
    door_rr_1_3: THREE.Mesh;
    door_rr_1_4: THREE.Mesh;
    door_rr_1_5: THREE.Mesh;
    door_rr_1_6: THREE.Mesh;
    door_rr_1_7: THREE.Mesh;
    door_rr_1_8: THREE.Mesh;
    window_rm: THREE.Mesh;
    enginebay_1: THREE.Mesh;
    enginebay_1_1: THREE.Mesh;
    enginebay_1_2: THREE.Mesh;
    enginebay_1_3: THREE.Mesh;
    enginebay_1_4: THREE.Mesh;
    enginebay_1_5: THREE.Mesh;
    enginebay_1_6: THREE.Mesh;
    enginebay_1_7: THREE.Mesh;
    enginebay_1_8: THREE.Mesh;
    enginebay_1_9: THREE.Mesh;
    enginebay_1_10: THREE.Mesh;
    engine_1: THREE.Mesh;
    engine_1_1: THREE.Mesh;
    engine_1_2: THREE.Mesh;
    engine_1_3: THREE.Mesh;
    engine_1_4: THREE.Mesh;
    engine_1_5: THREE.Mesh;
    engine_1_6: THREE.Mesh;
    engine_1_7: THREE.Mesh;
    engine_1_8: THREE.Mesh;
    seat_1: THREE.Mesh;
    seat_1_1: THREE.Mesh;
    seat_1_2: THREE.Mesh;
    seat_1_3: THREE.Mesh;
    seat_1_4: THREE.Mesh;
    seat_1_5: THREE.Mesh;
    seat_1_6: THREE.Mesh;
    seat_1_7: THREE.Mesh;
    seat_1_8: THREE.Mesh;
    seat_1_9: THREE.Mesh;
    headlight_l: THREE.Mesh;
    headlight_r: THREE.Mesh;
    taillight_l: THREE.Mesh;
    indicator_lr_1: THREE.Mesh;
    indicator_lr_1_1: THREE.Mesh;
    indicator_rr_1: THREE.Mesh;
    indicator_rr_1_1: THREE.Mesh;
    brakelight_l_1: THREE.Mesh;
    brakelight_l_1_1: THREE.Mesh;
    brakelight_l_1_2: THREE.Mesh;
    brakelight_r_1: THREE.Mesh;
    brakelight_r_1_1: THREE.Mesh;
    brakelight_r_1_2: THREE.Mesh;
    foglamp_1_1: THREE.Mesh;
    foglamp_1_1_1: THREE.Mesh;
    foglamp_2_1: THREE.Mesh;
    foglamp_2_1_1: THREE.Mesh;
    grille_1: THREE.Mesh;
    grille_1_1: THREE.Mesh;
    grille_1_2: THREE.Mesh;
    grille_1_3: THREE.Mesh;
    window_lr: THREE.Mesh;
    window_rr: THREE.Mesh;
    windscreen_1: THREE.Mesh;
    windscreen_1_1: THREE.Mesh;
    wheel_lf_1: THREE.Mesh;
    wheel_lf_1_1: THREE.Mesh;
    wheel_lf_1_2: THREE.Mesh;
    wheel_lf_1_3: THREE.Mesh;
    roof_rail_1: THREE.Mesh;
    roof_rail_1_1: THREE.Mesh;
    caliper_lf: THREE.Mesh;
    caliper_rf: THREE.Mesh;
    caliper_lr: THREE.Mesh;
    caliper_rr: THREE.Mesh;
    steeringwheel_1: THREE.Mesh;
    steeringwheel_1_1: THREE.Mesh;
    steeringwheel_1_2: THREE.Mesh;
    steeringwheel_1_3: THREE.Mesh;
    steeringwheel_1_4: THREE.Mesh;
    steeringwheel_1_5: THREE.Mesh;
    glass_1: THREE.Mesh;
    glass_1_1: THREE.Mesh;
    wheel_lr_1: THREE.Mesh;
    wheel_lr_1_1: THREE.Mesh;
    wheel_lr_1_2: THREE.Mesh;
    wheel_lr_1_3: THREE.Mesh;
    wheel_rf_1: THREE.Mesh;
    wheel_rf_1_1: THREE.Mesh;
    wheel_rf_1_2: THREE.Mesh;
    wheel_rf_1_3: THREE.Mesh;
    wheel_rr_1: THREE.Mesh;
    wheel_rr_1_1: THREE.Mesh;
    wheel_rr_1_2: THREE.Mesh;
    wheel_rr_1_3: THREE.Mesh;
    logo_rear: THREE.Mesh;
  };
  materials: {
    black: THREE.MeshStandardMaterial;
    lights: THREE.MeshStandardMaterial;
    caliper: THREE.MeshStandardMaterial;
    symbol_cockpit: THREE.MeshStandardMaterial;
    door: THREE.MeshStandardMaterial;
    stitch: THREE.MeshStandardMaterial;
    seatbelt: THREE.MeshStandardMaterial;
    screw_3: THREE.MeshStandardMaterial;
    alcantara_grey2: THREE.MeshStandardMaterial;
    symbols: THREE.MeshStandardMaterial;
    int_black: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    paint: THREE.MeshStandardMaterial;
    speaker: THREE.MeshStandardMaterial;
    alcantara_black: THREE.MeshStandardMaterial;
    carpet: THREE.MeshStandardMaterial;
    rpm: THREE.MeshStandardMaterial;
    head_unit: THREE.MeshStandardMaterial;
    gauges: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
    undercarriage: THREE.MeshStandardMaterial;
    screw_2: THREE.MeshStandardMaterial;
    lights_2: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    information: THREE.MeshStandardMaterial;
    screw_1: THREE.MeshStandardMaterial;
    red2: THREE.MeshStandardMaterial;
    yellow: THREE.MeshStandardMaterial;
    green: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    alcantara_seat: THREE.MeshStandardMaterial;
    rims_metal: THREE.MeshStandardMaterial;
    tyre: THREE.MeshStandardMaterial;
    disk: THREE.MeshStandardMaterial;
  };
};

export const Model = forwardRef((props: JSX.IntrinsicElements['group'] & { color: string }, ref) => {
  const { nodes, materials } = useGLTF(glbModel, dracoPath) as GLTFResult;

  const leftDoorRef = useRef();
  const groupRef = useRef();

  // const blackMaterial = {
  //   color: 'green',
  //   // color: '#000',
  //   metalness: 0.1,
  //   roughness: 0.5,
  // };

  const glassClearMaterial = {
    color: '#fff',
    transparent: true,
    metalness: 0,
    roughness: 0.1,
    opacity: 0.6,
  };
  const glassLightMaterial = {
    color: '#fff',
    transparent: true,
    metalness: 0,
    roughness: 0.1,
    opacity: 0.4,
  };

  const lightGlassMaterial = new THREE.MeshStandardMaterial({
    color: '#fff',
    transparent: true,
    metalness: 0,
    roughness: 0,
    opacity: 0.2,
  });
  // const logoMaterial = new THREE.MeshStandardMaterial({
  //   color: '#000',
  //   // transparent: true,
  //   metalness: 0,
  //   roughness: 0,
  //   // opacity: 0.2,
  // });

  useImperativeHandle(ref, () => ({
    leftDoor: leftDoorRef.current,
    model: groupRef.current,
  }));

  // useEffect(() => {
  //   const bgGeometry = new THREE.PlaneGeometry(100, 100); // replace 100 with the appropriate size to cover the group
  //   const bgMaterial = new THREE.MeshBasicMaterial({ color: 'green' }); // replace 0xff0000 with the desired color
  //   const bgMesh = new THREE.Mesh(bgGeometry, bgMaterial);
  //   bgMesh.position.copy(leftDoorRef.current.position);
  //   bgMesh.rotation.copy(leftDoorRef.current.rotation);
  //   leftDoorRef.current.add(bgMesh);

  // }, []);

  return (
    <group {...props} dispose={null} ref={groupRef}>
      {/* <axesHelper args={[10]} /> */}
      {/* <BallHelper radius={0.4} color="green" /> */}
      <group name="chassis" userData={{ name: 'chassis' }}>
        <mesh
          castShadow
          receiveShadow
          name="chassis_1"
          geometry={nodes.chassis_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_1"
          geometry={nodes.chassis_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_2"
          geometry={nodes.chassis_1_2.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_3"
          geometry={nodes.chassis_1_3.geometry}
          material={materials.symbol_cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_4"
          geometry={nodes.chassis_1_4.geometry}
          material={materials.door}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_5"
          geometry={nodes.chassis_1_5.geometry}
          material={materials.stitch}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_6"
          geometry={nodes.chassis_1_6.geometry}
          material={materials.seatbelt}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_7"
          geometry={nodes.chassis_1_7.geometry}
          material={materials.screw_3}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_8"
          geometry={nodes.chassis_1_8.geometry}
          material={materials.alcantara_grey2}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_9"
          geometry={nodes.chassis_1_9.geometry}
          material={materials.symbols}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_10"
          geometry={nodes.chassis_1_10.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_11"
          geometry={nodes.chassis_1_11.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_12"
          geometry={nodes.chassis_1_12.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_13"
          geometry={nodes.chassis_1_13.geometry}
          material={materials.speaker}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_14"
          geometry={nodes.chassis_1_14.geometry}
          material={materials.alcantara_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_15"
          geometry={nodes.chassis_1_15.geometry}
          material={materials.carpet}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_16"
          geometry={nodes.chassis_1_16.geometry}
          material={materials.rpm}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_17"
          geometry={nodes.chassis_1_17.geometry}
          material={materials.head_unit}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_18"
          geometry={nodes.chassis_1_18.geometry}
          material={materials.gauges}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_19"
          geometry={nodes.chassis_1_19.geometry}
          material={materials.Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          name="chassis_1_20"
          geometry={nodes.chassis_1_20.geometry}
          material={materials.screen}
        />
      </group>
      <group name="bumper_r" userData={{ name: 'bumper_r' }}>
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1"
          geometry={nodes.bumper_r_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1_1"
          geometry={nodes.bumper_r_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1_2"
          geometry={nodes.bumper_r_1_2.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1_3"
          geometry={nodes.bumper_r_1_3.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1_4"
          geometry={nodes.bumper_r_1_4.geometry}
          material={materials.undercarriage}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_r_1_5"
          geometry={nodes.bumper_r_1_5.geometry}
          material={materials.screw_2}
        />
      </group>
      <group name="bumper_f" userData={{ name: 'bumper_f' }}>
        <mesh
          castShadow
          receiveShadow
          name="bumper_f_1"
          geometry={nodes.bumper_f_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_f_1_1"
          geometry={nodes.bumper_f_1_1.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_f_1_2"
          geometry={nodes.bumper_f_1_2.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="bumper_f_1_3"
          geometry={nodes.bumper_f_1_3.geometry}
          material={materials.paint}
        />
      </group>
      <group name="indicator_rf" userData={{ name: 'indicator_rf' }}>
        <mesh
          castShadow
          receiveShadow
          name="indicator_rf_1"
          geometry={nodes.indicator_rf_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="indicator_rf_1_1"
          geometry={nodes.indicator_rf_1_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
      </group>
      <group name="indicator_lf" userData={{ name: 'indicator_lf' }}>
        <mesh
          castShadow
          receiveShadow
          name="indicator_lf_1"
          geometry={nodes.indicator_lf_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          name="indicator_lf_1_1"
          geometry={nodes.indicator_lf_1_1.geometry}
          material={materials.lights}
        />
      </group>
      <group name="bonnet" userData={{ name: 'bonnet' }}>
        <mesh castShadow receiveShadow name="bonnet_1" geometry={nodes.bonnet_1.geometry} material={materials.black} />
        <mesh
          castShadow
          receiveShadow
          name="bonnet_1_1"
          geometry={nodes.bonnet_1_1.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="bonnet_1_2"
          geometry={nodes.bonnet_1_2.geometry}
          material={materials.information}
        />
        <mesh
          castShadow
          receiveShadow
          name="bonnet_1_3"
          geometry={nodes.bonnet_1_3.geometry}
          material={materials.paint}
        />
      </group>
      <group name="boot" userData={{ name: 'boot' }}>
        <mesh castShadow receiveShadow name="boot_1" geometry={nodes.boot_1.geometry} material={materials.paint} />
        <mesh castShadow receiveShadow name="boot_1_1" geometry={nodes.boot_1_1.geometry} material={materials.Chrome} />
        <mesh castShadow receiveShadow name="boot_1_2" geometry={nodes.boot_1_2.geometry} material={materials.black} />
        <mesh castShadow receiveShadow name="boot_1_3" geometry={nodes.boot_1_3.geometry} material={materials.lights} />
        <mesh
          castShadow
          receiveShadow
          name="boot_1_4"
          geometry={nodes.boot_1_4.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="boot_1_5"
          geometry={nodes.boot_1_5.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="boot_1_6"
          geometry={nodes.boot_1_6.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="boot_1_7"
          geometry={nodes.boot_1_7.geometry}
          material={materials.screw_1}
        />
        <mesh castShadow receiveShadow name="boot_1_8" geometry={nodes.boot_1_8.geometry} material={materials.red2} />
      </group>
      <mesh
        name="reversinglight_r"
        geometry={nodes.reversinglight_r.geometry}
        material={materials.lights}
        userData={{ name: 'reversinglight_r' }}
      />
      <mesh
        name="reversinglight_l"
        geometry={nodes.reversinglight_l.geometry}
        material={materials.lights}
        userData={{ name: 'reversinglight_l' }}
      />
      <group name="brakelight_m" userData={{ name: 'brakelight_m' }}>
        <mesh
          castShadow
          receiveShadow
          name="brakelight_m_1"
          geometry={nodes.brakelight_m_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="brakelight_m_1_1"
          geometry={nodes.brakelight_m_1_1.geometry}
          material={materials.lights_2}
        />
      </group>
      <group name="taillight_r" userData={{ name: 'taillight_r' }}>
        <mesh
          castShadow
          receiveShadow
          name="taillight_r_1"
          geometry={nodes.taillight_r_1.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="taillight_r_1_1"
          geometry={nodes.taillight_r_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="taillight_r_1_2"
          geometry={nodes.taillight_r_1_2.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
      </group>
      <group name="windscreen_r" userData={{ name: 'windscreen_r' }}>
        <mesh
          castShadow
          receiveShadow
          name="windscreen_r_1"
          geometry={nodes.windscreen_r_1.geometry}
          material={materials.glass}
        >
          {/* <meshStandardMaterial {...bodyMaterial} /> */}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          name="windscreen_r_1_1"
          geometry={nodes.windscreen_r_1_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassClearMaterial} />
        </mesh>
      </group>
      <group name="bodyshell" userData={{ name: 'bodyshell' }}>
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1"
          geometry={nodes.bodyshell_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_1"
          geometry={nodes.bodyshell_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_2"
          geometry={nodes.bodyshell_1_2.geometry}
          material={materials.information}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_3"
          geometry={nodes.bodyshell_1_3.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_4"
          geometry={nodes.bodyshell_1_4.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_5"
          geometry={nodes.bodyshell_1_5.geometry}
          material={materials.undercarriage}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_6"
          geometry={nodes.bodyshell_1_6.geometry}
          material={materials.screw_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="bodyshell_1_7"
          geometry={nodes.bodyshell_1_7.geometry}
          material={materials.red2}
        ></mesh>
      </group>

      {/* 左车门 */}

      {/* rotation={[0, -Math.PI / 2.4, 0]} position={[-63, 0, 0]} */}
      <group ref={leftDoorRef}>
        <group name="door_lf" userData={{ name: 'door_lf' }}>
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1"
            geometry={nodes.door_lf_1.geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_1"
            geometry={nodes.door_lf_1_1.geometry}
            material={materials.lights}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_2"
            geometry={nodes.door_lf_1_2.geometry}
            material={materials.lights_2}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_3"
            geometry={nodes.door_lf_1_3.geometry}
            material={materials.door}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_4"
            geometry={nodes.door_lf_1_4.geometry}
            material={materials.stitch}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_5"
            geometry={nodes.door_lf_1_5.geometry}
            material={materials.int_black}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_6"
            geometry={nodes.door_lf_1_6.geometry}
            material={materials.red}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_7"
            geometry={nodes.door_lf_1_7.geometry}
            material={materials.screw_1}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_8"
            geometry={nodes.door_lf_1_8.geometry}
            material={materials.paint}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_9"
            geometry={nodes.door_lf_1_9.geometry}
            material={materials.speaker}
          />
          <mesh
            castShadow
            receiveShadow
            name="door_lf_1_10"
            geometry={nodes.door_lf_1_10.geometry}
            material={materials.symbols}
          />
        </group>
        <mesh
          name="window_lf"
          geometry={nodes.window_lf.geometry}
          material={materials.glass}
          userData={{ name: 'window_lf' }}
        >
          <meshStandardMaterial {...glassClearMaterial} />
        </mesh>
      </group>
      <group name="door_rf" userData={{ name: 'door_rf' }}>
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1"
          geometry={nodes.door_rf_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_1"
          geometry={nodes.door_rf_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_2"
          geometry={nodes.door_rf_1_2.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_3"
          geometry={nodes.door_rf_1_3.geometry}
          material={materials.door}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_4"
          geometry={nodes.door_rf_1_4.geometry}
          material={materials.stitch}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_5"
          geometry={nodes.door_rf_1_5.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_6"
          geometry={nodes.door_rf_1_6.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_7"
          geometry={nodes.door_rf_1_7.geometry}
          material={materials.screw_1}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_8"
          geometry={nodes.door_rf_1_8.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_9"
          geometry={nodes.door_rf_1_9.geometry}
          material={materials.speaker}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rf_1_10"
          geometry={nodes.door_rf_1_10.geometry}
          material={materials.symbols}
        />
      </group>
      <mesh
        name="window_rf"
        geometry={nodes.window_rf.geometry}
        material={materials.glass}
        userData={{ name: 'window_rf' }}
      >
        <meshStandardMaterial {...glassClearMaterial} />
      </mesh>
      <group name="door_lr" userData={{ name: 'door_lr' }}>
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1"
          geometry={nodes.door_lr_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_1"
          geometry={nodes.door_lr_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_2"
          geometry={nodes.door_lr_1_2.geometry}
          material={materials.door}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_3"
          geometry={nodes.door_lr_1_3.geometry}
          material={materials.stitch}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_4"
          geometry={nodes.door_lr_1_4.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_5"
          geometry={nodes.door_lr_1_5.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_6"
          geometry={nodes.door_lr_1_6.geometry}
          material={materials.screw_1}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_7"
          geometry={nodes.door_lr_1_7.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_lr_1_8"
          geometry={nodes.door_lr_1_8.geometry}
          material={materials.speaker}
        />
      </group>
      <mesh
        name="window_lm"
        geometry={nodes.window_lm.geometry}
        material={materials.glass}
        userData={{ name: 'window_lm' }}
      >
        <meshStandardMaterial {...glassClearMaterial} />
      </mesh>
      <group name="door_rr" userData={{ name: 'door_rr' }}>
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1"
          geometry={nodes.door_rr_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_1"
          geometry={nodes.door_rr_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_2"
          geometry={nodes.door_rr_1_2.geometry}
          material={materials.door}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_3"
          geometry={nodes.door_rr_1_3.geometry}
          material={materials.stitch}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_4"
          geometry={nodes.door_rr_1_4.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_5"
          geometry={nodes.door_rr_1_5.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_6"
          geometry={nodes.door_rr_1_6.geometry}
          material={materials.screw_1}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_7"
          geometry={nodes.door_rr_1_7.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="door_rr_1_8"
          geometry={nodes.door_rr_1_8.geometry}
          material={materials.speaker}
        />
      </group>
      <mesh
        name="window_rm"
        geometry={nodes.window_rm.geometry}
        material={materials.glass}
        userData={{ name: 'window_rm' }}
      >
        <meshStandardMaterial {...glassClearMaterial} />
      </mesh>
      <group name="enginebay" userData={{ name: 'enginebay' }}>
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1"
          geometry={nodes.enginebay_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_1"
          geometry={nodes.enginebay_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_2"
          geometry={nodes.enginebay_1_2.geometry}
          material={materials.symbol_cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_3"
          geometry={nodes.enginebay_1_3.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_4"
          geometry={nodes.enginebay_1_4.geometry}
          material={materials.information}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_5"
          geometry={nodes.enginebay_1_5.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_6"
          geometry={nodes.enginebay_1_6.geometry}
          material={materials.green}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_7"
          geometry={nodes.enginebay_1_7.geometry}
          material={materials.blue}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_8"
          geometry={nodes.enginebay_1_8.geometry}
          material={materials.screw_1}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_9"
          geometry={nodes.enginebay_1_9.geometry}
          material={materials.paint}
        />
        <mesh
          castShadow
          receiveShadow
          name="enginebay_1_10"
          geometry={nodes.enginebay_1_10.geometry}
          material={materials.white}
        />
      </group>
      <group name="engine" userData={{ name: 'engine' }}>
        <mesh castShadow receiveShadow name="engine_1" geometry={nodes.engine_1.geometry} material={materials.black} />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_1"
          geometry={nodes.engine_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_2"
          geometry={nodes.engine_1_2.geometry}
          material={materials.symbol_cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_3"
          geometry={nodes.engine_1_3.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_4"
          geometry={nodes.engine_1_4.geometry}
          material={materials.red}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_5"
          geometry={nodes.engine_1_5.geometry}
          material={materials.information}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_6"
          geometry={nodes.engine_1_6.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_7"
          geometry={nodes.engine_1_7.geometry}
          material={materials.green}
        />
        <mesh
          castShadow
          receiveShadow
          name="engine_1_8"
          geometry={nodes.engine_1_8.geometry}
          material={materials.blue}
        />
      </group>
      <group name="seat" userData={{ name: 'seat' }}>
        <mesh castShadow receiveShadow name="seat_1" geometry={nodes.seat_1.geometry} material={materials.black} />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_1"
          geometry={nodes.seat_1_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_2"
          geometry={nodes.seat_1_2.geometry}
          material={materials.symbol_cockpit}
        />
        <mesh castShadow receiveShadow name="seat_1_3" geometry={nodes.seat_1_3.geometry} material={materials.door} />
        <mesh castShadow receiveShadow name="seat_1_4" geometry={nodes.seat_1_4.geometry} material={materials.stitch} />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_5"
          geometry={nodes.seat_1_5.geometry}
          material={materials.seatbelt}
        />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_6"
          geometry={nodes.seat_1_6.geometry}
          material={materials.screw_3}
        />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_7"
          geometry={nodes.seat_1_7.geometry}
          material={materials.alcantara_grey2}
        />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_8"
          geometry={nodes.seat_1_8.geometry}
          material={materials.alcantara_seat}
        />
        <mesh
          castShadow
          receiveShadow
          name="seat_1_9"
          geometry={nodes.seat_1_9.geometry}
          material={materials.symbols}
        />
      </group>
      {/* 车前灯泡 */}
      <mesh
        name="headlight_l"
        geometry={nodes.headlight_l.geometry}
        material={materials.lights}
        userData={{ name: 'headlight_l' }}
      ></mesh>
      <mesh
        name="headlight_r"
        geometry={nodes.headlight_r.geometry}
        material={materials.lights}
        userData={{ name: 'headlight_r' }}
      ></mesh>

      <mesh
        name="taillight_l"
        geometry={nodes.taillight_l.geometry}
        material={materials.lights}
        userData={{ name: 'taillight_l' }}
      />
      <group name="indicator_lr" userData={{ name: 'indicator_lr' }}>
        <mesh
          castShadow
          receiveShadow
          name="indicator_lr_1"
          geometry={nodes.indicator_lr_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="indicator_lr_1_1"
          geometry={nodes.indicator_lr_1_1.geometry}
          material={materials.lights_2}
        />
      </group>
      <group name="indicator_rr" userData={{ name: 'indicator_rr' }}>
        <mesh
          castShadow
          receiveShadow
          name="indicator_rr_1"
          geometry={nodes.indicator_rr_1.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="indicator_rr_1_1"
          geometry={nodes.indicator_rr_1_1.geometry}
          material={materials.lights}
        />
      </group>
      <group name="brakelight_l" userData={{ name: 'brakelight_l' }}>
        <mesh
          castShadow
          receiveShadow
          name="brakelight_l_1"
          geometry={nodes.brakelight_l_1.geometry}
          material={materials.lights_2}
        />
        <mesh
          castShadow
          receiveShadow
          name="brakelight_l_1_1"
          geometry={nodes.brakelight_l_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="brakelight_l_1_2"
          geometry={nodes.brakelight_l_1_2.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
      </group>
      <group name="brakelight_r" userData={{ name: 'brakelight_r' }}>
        <mesh
          castShadow
          receiveShadow
          name="brakelight_r_1"
          geometry={nodes.brakelight_r_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          name="brakelight_r_1_1"
          geometry={nodes.brakelight_r_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="brakelight_r_1_2"
          geometry={nodes.brakelight_r_1_2.geometry}
          material={materials.lights_2}
        />
      </group>
      <group name="foglamp_1" userData={{ name: 'foglamp_1' }}>
        <mesh
          castShadow
          receiveShadow
          name="foglamp_1_1"
          geometry={nodes.foglamp_1_1.geometry}
          material={materials.lights}
        />
        <mesh
          castShadow
          receiveShadow
          name="foglamp_1_1_1"
          geometry={nodes.foglamp_1_1_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
      </group>
      <group name="foglamp_2" userData={{ name: 'foglamp_2' }}>
        <mesh
          castShadow
          receiveShadow
          name="foglamp_2_1"
          geometry={nodes.foglamp_2_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassLightMaterial} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          name="foglamp_2_1_1"
          geometry={nodes.foglamp_2_1_1.geometry}
          material={materials.lights}
        />
      </group>
      <group name="grille" userData={{ name: 'grille' }}>
        <mesh castShadow receiveShadow name="grille_1" geometry={nodes.grille_1.geometry} material={materials.Chrome}>
          {/* <meshStandardMaterial {...blackMaterial} /> */}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          name="grille_1_1"
          geometry={nodes.grille_1_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="grille_1_2"
          geometry={nodes.grille_1_2.geometry}
          material={materials.int_black}
        />
        <mesh
          castShadow
          receiveShadow
          name="grille_1_3"
          geometry={nodes.grille_1_3.geometry}
          material={materials.lights}
        />
      </group>
      <mesh
        name="window_lr"
        geometry={nodes.window_lr.geometry}
        material={materials.glass}
        userData={{ name: 'window_lr' }}
      >
        <meshStandardMaterial {...glassClearMaterial} />
      </mesh>
      <mesh
        name="window_rr"
        geometry={nodes.window_rr.geometry}
        material={materials.glass}
        userData={{ name: 'window_rr' }}
      >
        <meshStandardMaterial {...glassClearMaterial} />
      </mesh>
      <group name="windscreen" userData={{ name: 'windscreen' }}>
        <mesh
          castShadow
          receiveShadow
          name="windscreen_1"
          geometry={nodes.windscreen_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="windscreen_1_1"
          geometry={nodes.windscreen_1_1.geometry}
          material={materials.glass}
        >
          <meshStandardMaterial {...glassClearMaterial} />
        </mesh>
      </group>
      <group name="wheel_lf" userData={{ name: 'wheel_lf' }}>
        <mesh
          castShadow
          receiveShadow
          name="wheel_lf_1"
          geometry={nodes.wheel_lf_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lf_1_1"
          geometry={nodes.wheel_lf_1_1.geometry}
          material={materials.rims_metal}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lf_1_2"
          geometry={nodes.wheel_lf_1_2.geometry}
          material={materials.tyre}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lf_1_3"
          geometry={nodes.wheel_lf_1_3.geometry}
          material={materials.disk}
        />
      </group>
      <group name="roof_rail" userData={{ name: 'roof_rail' }}>
        <mesh
          castShadow
          receiveShadow
          name="roof_rail_1"
          geometry={nodes.roof_rail_1.geometry}
          material={materials.Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          name="roof_rail_1_1"
          geometry={nodes.roof_rail_1_1.geometry}
          material={materials.black}
        />
      </group>
      <mesh
        name="caliper_lf"
        geometry={nodes.caliper_lf.geometry}
        material={materials.caliper}
        userData={{ name: 'caliper_lf' }}
      />
      <mesh
        name="caliper_rf"
        geometry={nodes.caliper_rf.geometry}
        material={materials.caliper}
        userData={{ name: 'caliper_rf' }}
      />
      <mesh
        name="caliper_lr"
        geometry={nodes.caliper_lr.geometry}
        material={materials.caliper}
        userData={{ name: 'caliper_lr' }}
      />
      <mesh
        name="caliper_rr"
        geometry={nodes.caliper_rr.geometry}
        material={materials.caliper}
        userData={{ name: 'caliper_rr' }}
      />
      <group name="steeringwheel" userData={{ name: 'steeringwheel' }}>
        <mesh
          castShadow
          receiveShadow
          name="steeringwheel_1"
          geometry={nodes.steeringwheel_1.geometry}
          material={materials.caliper}
        />
        <mesh
          castShadow
          receiveShadow
          name="steeringwheel_1_1"
          geometry={nodes.steeringwheel_1_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="steeringwheel_1_2"
          geometry={nodes.steeringwheel_1_2.geometry}
          material={materials.symbols}
        />
        <mesh
          name="steeringwheel_1_3"
          geometry={nodes.steeringwheel_1_3.geometry}
          material={materials.symbol_cockpit}
        />
        <mesh
          castShadow
          receiveShadow
          name="steeringwheel_1_4"
          geometry={nodes.steeringwheel_1_4.geometry}
          material={materials.stitch}
        />
        <mesh
          castShadow
          receiveShadow
          name="steeringwheel_1_5"
          geometry={nodes.steeringwheel_1_5.geometry}
          material={materials.int_black}
        />
      </group>
      <group name="glass" userData={{ name: 'glass' }}>
        <mesh
          castShadow
          receiveShadow
          name="glass_1"
          geometry={nodes.glass_1.geometry}
          material={lightGlassMaterial}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          name="glass_1_1"
          geometry={nodes.glass_1_1.geometry}
          material={lightGlassMaterial}
        ></mesh>
      </group>
      <group name="wheel_lr" userData={{ name: 'wheel_lr' }}>
        <mesh
          castShadow
          receiveShadow
          name="wheel_lr_1"
          geometry={nodes.wheel_lr_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lr_1_1"
          geometry={nodes.wheel_lr_1_1.geometry}
          material={materials.rims_metal}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lr_1_2"
          geometry={nodes.wheel_lr_1_2.geometry}
          material={materials.tyre}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_lr_1_3"
          geometry={nodes.wheel_lr_1_3.geometry}
          material={materials.disk}
        />
      </group>
      <group name="wheel_rf" userData={{ name: 'wheel_rf' }}>
        <mesh
          castShadow
          receiveShadow
          name="wheel_rf_1"
          geometry={nodes.wheel_rf_1.geometry}
          material={materials.disk}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rf_1_1"
          geometry={nodes.wheel_rf_1_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rf_1_2"
          geometry={nodes.wheel_rf_1_2.geometry}
          material={materials.rims_metal}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rf_1_3"
          geometry={nodes.wheel_rf_1_3.geometry}
          material={materials.tyre}
        />
      </group>
      <group name="wheel_rr" userData={{ name: 'wheel_rr' }}>
        <mesh
          castShadow
          receiveShadow
          name="wheel_rr_1"
          geometry={nodes.wheel_rr_1.geometry}
          material={materials.disk}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rr_1_1"
          geometry={nodes.wheel_rr_1_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rr_1_2"
          geometry={nodes.wheel_rr_1_2.geometry}
          material={materials.rims_metal}
        />
        <mesh
          castShadow
          receiveShadow
          name="wheel_rr_1_3"
          geometry={nodes.wheel_rr_1_3.geometry}
          material={materials.tyre}
        />
      </group>
    </group>
  );
});

useGLTF.preload(glbModel, dracoPath);
