/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 md.glb -T -k -t -m
*/

import { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

import glbModel from '@/assets/model/md-transformed.glb';
import { dracoPath } from '@/constant';

type GLTFResult = GLTF & {
  nodes: {
    windows_part_07: THREE.Mesh;
    Body_00: THREE.Mesh;
    window_parts_002: THREE.Mesh;
    mirror_part: THREE.Mesh;
    mirror01: THREE.Mesh;
    mirror_glass: THREE.Mesh;
    Body_01: THREE.Mesh;
    bottom01: THREE.Mesh;
    trunk_weatherstrip: THREE.Mesh;
    interior_part_03: THREE.Mesh;
    Body_02: THREE.Mesh;
    bumper_part_03: THREE.Mesh;
    gablight_02: THREE.Mesh;
    Body_03: THREE.Mesh;
    gablight_00: THREE.Mesh;
    bumper_part_01: THREE.Mesh;
    face_part_06: THREE.Mesh;
    face_part_05: THREE.Mesh;
    Body_04: THREE.Mesh;
    headlight_16: THREE.Mesh;
    face_part_14: THREE.Mesh;
    face_part_01: THREE.Mesh;
    face_part_10: THREE.Mesh;
    face_part_08: THREE.Mesh;
    face_part_00: THREE.Mesh;
    face_part_09: THREE.Mesh;
    face_part_12: THREE.Mesh;
    face_part_13: THREE.Mesh;
    Body_05: THREE.Mesh;
    dvornik_00: THREE.Mesh;
    Body_06: THREE.Mesh;
    face_part_03: THREE.Mesh;
    face_part_02: THREE.Mesh;
    face_part_15: THREE.Mesh;
    face_part_04: THREE.Mesh;
    face_part_11: THREE.Mesh;
    headlight_10: THREE.Mesh;
    headlight_00: THREE.Mesh;
    headlight_04: THREE.Mesh;
    headlight_02: THREE.Mesh;
    headlight_03: THREE.Mesh;
    headlight_05: THREE.Mesh;
    headlight_15: THREE.Mesh;
    headlight_13: THREE.Mesh;
    headlight_19: THREE.Mesh;
    headlight_11: THREE.Mesh;
    headlight_21: THREE.Mesh;
    headlight_01: THREE.Mesh;
    headlight_18: THREE.Mesh;
    headlight_22: THREE.Mesh;
    headlight_08: THREE.Mesh;
    headlight_07: THREE.Mesh;
    headlight_14: THREE.Mesh;
    headlight_09: THREE.Mesh;
    headlight_17: THREE.Mesh;
    headlight_06: THREE.Mesh;
    headlight_20: THREE.Mesh;
    headlight_23: THREE.Mesh;
    headlight_12: THREE.Mesh;
    headlight_24: THREE.Mesh;
    headlight_25: THREE.Mesh;
    headlight_26: THREE.Mesh;
    Body_07: THREE.Mesh;
    Body_08: THREE.Mesh;
    windows_part_02: THREE.Mesh;
    Body_09: THREE.Mesh;
    windows_part_04: THREE.Mesh;
    Body_10: THREE.Mesh;
    Body_11: THREE.Mesh;
    black_00: THREE.Mesh;
    roof: THREE.Mesh;
    Body_12: THREE.Mesh;
    windows_part_01: THREE.Mesh;
    windows_part_05: THREE.Mesh;
    interior_part_01: THREE.Mesh;
    X_chrome: THREE.Mesh;
    windows_part_09: THREE.Mesh;
    bumper_part_00: THREE.Mesh;
    Body_13: THREE.Mesh;
    black_02: THREE.Mesh;
    bumper_part_02: THREE.Mesh;
    bottom02: THREE.Mesh;
    redglass01: THREE.Mesh;
    Body_14: THREE.Mesh;
    interior_part_00: THREE.Mesh;
    interior_part_04: THREE.Mesh;
    windows_part_03: THREE.Mesh;
    windows_part_11: THREE.Mesh;
    interior_part_02: THREE.Mesh;
    gablight_03: THREE.Mesh;
    gablight_04: THREE.Mesh;
    gablight_05: THREE.Mesh;
    gablight_06: THREE.Mesh;
    gablight_07: THREE.Mesh;
    gablight_01: THREE.Mesh;
    XDrive: THREE.Mesh;
    face_part_07: THREE.Mesh;
    Body_15: THREE.Mesh;
    black_01: THREE.Mesh;
    bumper_part_04: THREE.Mesh;
    windows_part_10: THREE.Mesh;
    windows_part_08: THREE.Mesh;
    windows_part_06: THREE.Mesh;
    M5_Logo_Part_006: THREE.Mesh;
    M5_Logo_Part_007: THREE.Mesh;
    M5_Logo_Part_008: THREE.Mesh;
    M5_Logo_Part_009: THREE.Mesh;
    M5_Logo_Part_010: THREE.Mesh;
    M5_Logo_Part_03: THREE.Mesh;
    M5_Logo_Part_02: THREE.Mesh;
    M5_Logo_Part_01: THREE.Mesh;
    M5_Logo_Part_05: THREE.Mesh;
    M5_Logo_Part_04: THREE.Mesh;
    dvornik_02: THREE.Mesh;
    dvornik_01: THREE.Mesh;
    logo_06: THREE.Mesh;
    logo_05: THREE.Mesh;
    logo_01: THREE.Mesh;
    logo_02: THREE.Mesh;
    logo_04: THREE.Mesh;
    logo_03: THREE.Mesh;
    logo_08: THREE.Mesh;
    logo_10: THREE.Mesh;
    logo_11: THREE.Mesh;
    logo_12: THREE.Mesh;
    logo_09: THREE.Mesh;
    logo_07: THREE.Mesh;
    trunk_rubber: THREE.Mesh;
    XDrive_dark: THREE.Mesh;
    wh_fl_03: THREE.Mesh;
    wh_fr_08: THREE.Mesh;
    wh_fl_01: THREE.Mesh;
    wh_fr_09: THREE.Mesh;
    wh_fl_00: THREE.Mesh;
    wh_fr_00: THREE.Mesh;
    wh_fl_12: THREE.Mesh;
    wh_fr_11: THREE.Mesh;
    wh_fl_02: THREE.Mesh;
    wh_fl_04: THREE.Mesh;
    wh_fl_05: THREE.Mesh;
    wh_fl_06: THREE.Mesh;
    wh_fl_07: THREE.Mesh;
    wh_fl_08: THREE.Mesh;
    wh_fl_09: THREE.Mesh;
    wh_fl_10: THREE.Mesh;
    wh_fl_11: THREE.Mesh;
    wh_fr_12: THREE.Mesh;
    wh_fr_01: THREE.Mesh;
    wh_fr_02: THREE.Mesh;
    wh_fr_03: THREE.Mesh;
    wh_fr_04: THREE.Mesh;
    wh_fr_05: THREE.Mesh;
    wh_fr_06: THREE.Mesh;
    wh_fr_07: THREE.Mesh;
    wh_fr_10: THREE.Mesh;
    wh_fl_13: THREE.Mesh;
    wh_fr_13: THREE.Mesh;
    wh_fl_14: THREE.Mesh;
    wh_fr_14: THREE.Mesh;
    wh_fl_15: THREE.Mesh;
    wh_fr_15: THREE.Mesh;
    wh_fl_16: THREE.Mesh;
    wh_fl_17: THREE.Mesh;
    wh_fl_18: THREE.Mesh;
    wh_fl_19: THREE.Mesh;
    wh_fl_20: THREE.Mesh;
    wh_fl_21: THREE.Mesh;
    wh_fl_22: THREE.Mesh;
    wh_fl_23: THREE.Mesh;
    wh_fl_24: THREE.Mesh;
    wh_fr_16: THREE.Mesh;
    wh_fr_17: THREE.Mesh;
    wh_fr_18: THREE.Mesh;
    wh_fr_19: THREE.Mesh;
    wh_fr_20: THREE.Mesh;
    wh_fr_21: THREE.Mesh;
    wh_fr_22: THREE.Mesh;
    wh_fr_23: THREE.Mesh;
    wh_fr_24: THREE.Mesh;
  };
  materials: {
    windowglass: THREE.MeshStandardMaterial;
    carpaint: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    mirror: THREE.MeshStandardMaterial;
    clearglass: THREE.MeshStandardMaterial;
    darkglass: THREE.MeshStandardMaterial;
    mattemetal: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    interior: THREE.MeshStandardMaterial;
    redglass: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    turquoise: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    brakedisk: THREE.MeshStandardMaterial;
    tire: THREE.MeshStandardMaterial;
    rim_second: THREE.MeshStandardMaterial;
    rim: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group'] & { color: string; seatColor: string }) {
  const { nodes, materials } = useGLTF(glbModel, dracoPath) as GLTFResult;
  const { color, seatColor = '#444', ...rest } = props;

  const bodyMaterial = useMemo(
    () => ({
      color: color,
      metalness: 1.0,
      roughness: 0.5,
    }),
    [color],
  );
  const seatMaterial = useMemo(
    () => ({
      color: seatColor,
      metalness: 0,
      roughness: 1,
    }),
    [seatColor],
  );

  const wheelMaterial = {
    color: '#333',
    metalness: 0,
    roughness: 1,
  };

  const floorMaterial = {
    color: '#282828',
    metalness: 0,
    roughness: 1,
  };
  const blackMaterial = {
    color: '#303030',
    metalness: 0,
    roughness: 1,
  };
  const matMaterial = {
    color: '#aaa',
    metalness: 0.5,
    roughness: 0.6,
  };
  const mirrorMaterial = {
    // color: '#fff',
    metalness: 1,
    roughness: 0,
    // envMaps:"reflection"
  };

  const redLight = {
    color: '#e80000',
    transparent: true,
    metalness: 0,
    roughness: 0.1,
    opacity: 0.3,
  };

  return (
    <group {...rest} dispose={null}>
      <group name="RootNode" userData={{ name: 'RootNode' }}>
        <group
          name="windows_part_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_07"
            geometry={nodes.windows_part_07.geometry}
            material={materials.windowglass}
            userData={{ name: 'windows_part_07' }}
          />
        </group>
        <group
          name="Body_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_00_$AssimpFbx$_Translation' }}
        >
          {/* 车轮框上方 */}
          <mesh
            name="Body_00"
            geometry={nodes.Body_00.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_00' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="window_parts_002_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'window_parts_002_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="window_parts_002"
            geometry={nodes.window_parts_002.geometry}
            material={materials.black}
            userData={{ name: 'window_parts_002' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="mirror_part_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'mirror_part_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="mirror_part"
            geometry={nodes.mirror_part.geometry}
            material={materials.chrome}
            userData={{ name: 'mirror_part' }}
          ></mesh>
        </group>
        <group
          name="mirror01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'mirror01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="mirror01"
            geometry={nodes.mirror01.geometry}
            material={materials.mirror}
            userData={{ name: 'mirror01' }}
          >
            <meshStandardMaterial {...mirrorMaterial} />
          </mesh>
        </group>
        <group
          name="mirror_glass_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'mirror_glass_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="mirror_glass"
            geometry={nodes.mirror_glass.geometry}
            material={materials.clearglass}
            userData={{ name: 'mirror_glass' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_01_$AssimpFbx$_Translation' }}
        >
          {/* 后视镜-上 */}
          <mesh
            name="Body_01"
            geometry={nodes.Body_01.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_01' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="bottom01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bottom01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bottom01"
            geometry={nodes.bottom01.geometry}
            material={materials.chrome}
            userData={{ name: 'bottom01' }}
          >
            <meshStandardMaterial {...matMaterial} />
          </mesh>
        </group>
        <group
          name="trunk_weatherstrip_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'trunk_weatherstrip_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="trunk_weatherstrip"
            geometry={nodes.trunk_weatherstrip.geometry}
            material={materials.black}
            userData={{ name: 'trunk_weatherstrip' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="interior_part_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'interior_part_03_$AssimpFbx$_Translation' }}
        >
          {/* 后玻璃框 */}
          <mesh
            name="interior_part_03"
            geometry={nodes.interior_part_03.geometry}
            material={materials.darkglass}
            userData={{ name: 'interior_part_03' }}
          ></mesh>
        </group>
        <group
          name="Body_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_02_$AssimpFbx$_Translation' }}
        >
          {/* 车顶尾巴 */}
          <mesh
            name="Body_02"
            geometry={nodes.Body_02.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_02' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="bumper_part_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bumper_part_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bumper_part_03"
            geometry={nodes.bumper_part_03.geometry}
            material={materials.chrome}
            userData={{ name: 'bumper_part_03' }}
          >
            <meshStandardMaterial {...matMaterial} />
          </mesh>
        </group>
        <group
          name="gablight_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_02"
            geometry={nodes.gablight_02.geometry}
            material={materials.black}
            userData={{ name: 'gablight_02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_03_$AssimpFbx$_Translation' }}
        >
          {/* 车背后 */}
          <mesh
            name="Body_03"
            geometry={nodes.Body_03.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_03' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="gablight_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_00"
            geometry={nodes.gablight_00.geometry}
            material={materials.clearglass}
            userData={{ name: 'gablight_00' }}
          />
        </group>
        <group
          name="bumper_part_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bumper_part_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bumper_part_01"
            geometry={nodes.bumper_part_01.geometry}
            material={materials.mattemetal}
            userData={{ name: 'bumper_part_01' }}
          >
            <meshStandardMaterial {...matMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_06"
            geometry={nodes.face_part_06.geometry}
            material={materials.black}
            userData={{ name: 'face_part_06' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_05"
            geometry={nodes.face_part_05.geometry}
            material={materials.clearglass}
            userData={{ name: 'face_part_05' }}
          />
        </group>
        <group
          name="Body_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_04_$AssimpFbx$_Translation' }}
        >
          {/* 车前方 */}
          <mesh
            name="Body_04"
            geometry={nodes.Body_04.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_04' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_16_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_16_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_16"
            geometry={nodes.headlight_16.geometry}
            material={materials.black}
            userData={{ name: 'headlight_16' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_14_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_14_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_14"
            geometry={nodes.face_part_14.geometry}
            material={materials.chrome}
            userData={{ name: 'face_part_14' }}
          />
        </group>
        <group
          name="face_part_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_01"
            geometry={nodes.face_part_01.geometry}
            material={materials.chrome}
            userData={{ name: 'face_part_01' }}
          />
        </group>
        <group
          name="face_part_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_10_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_10"
            geometry={nodes.face_part_10.geometry}
            material={materials.chrome}
            userData={{ name: 'face_part_10' }}
          />
        </group>
        <group
          name="face_part_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_08_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_08"
            geometry={nodes.face_part_08.geometry}
            material={materials.black}
            userData={{ name: 'face_part_08' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_00"
            geometry={nodes.face_part_00.geometry}
            material={materials.black}
            userData={{ name: 'face_part_00' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_09_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_09"
            geometry={nodes.face_part_09.geometry}
            material={materials.chrome}
            userData={{ name: 'face_part_09' }}
          />
        </group>
        <group
          name="face_part_12_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_12_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_12"
            geometry={nodes.face_part_12.geometry}
            material={materials.clearglass}
            userData={{ name: 'face_part_12' }}
          />
        </group>
        <group
          name="face_part_13_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_13_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_13"
            geometry={nodes.face_part_13.geometry}
            material={materials.black}
            userData={{ name: 'face_part_13' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_05_$AssimpFbx$_Translation' }}
        >
          {/* 车背后logo旁边像胶带 */}
          <mesh
            name="Body_05"
            geometry={nodes.Body_05.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_05' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="dvornik_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'dvornik_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="dvornik_00"
            geometry={nodes.dvornik_00.geometry}
            material={materials.black}
            userData={{ name: 'dvornik_00' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_06_$AssimpFbx$_Translation' }}
        >
          {/* 引擎盖 */}
          <mesh
            name="Body_06"
            geometry={nodes.Body_06.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_06' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_03"
            geometry={nodes.face_part_03.geometry}
            material={materials.black}
            userData={{ name: 'face_part_03' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_02"
            geometry={nodes.face_part_02.geometry}
            material={materials.black}
            userData={{ name: 'face_part_02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_15_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_15_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_15"
            geometry={nodes.face_part_15.geometry}
            material={materials.black}
            userData={{ name: 'face_part_15' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_04"
            geometry={nodes.face_part_04.geometry}
            material={materials.black}
            userData={{ name: 'face_part_04' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="face_part_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_11_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_11"
            geometry={nodes.face_part_11.geometry}
            material={materials.black}
            userData={{ name: 'face_part_11' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_10_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_10"
            geometry={nodes.headlight_10.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_10' }}
          />
        </group>
        <group
          name="headlight_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_00"
            geometry={nodes.headlight_00.geometry}
            material={materials.black}
            userData={{ name: 'headlight_00' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_04"
            geometry={nodes.headlight_04.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_04' }}
          />
        </group>
        <group
          name="headlight_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_02"
            geometry={nodes.headlight_02.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_02' }}
          />
        </group>
        <group
          name="headlight_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_03"
            geometry={nodes.headlight_03.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_03' }}
          />
        </group>
        <group
          name="headlight_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_05"
            geometry={nodes.headlight_05.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_05' }}
          />
        </group>
        <group
          name="headlight_15_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_15_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_15"
            geometry={nodes.headlight_15.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_15' }}
          />
        </group>
        <group
          name="headlight_13_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_13_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_13"
            geometry={nodes.headlight_13.geometry}
            material={materials.black}
            userData={{ name: 'headlight_13' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_19_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_19_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_19"
            geometry={nodes.headlight_19.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_19' }}
          />
        </group>
        <group
          name="headlight_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_11_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_11"
            geometry={nodes.headlight_11.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_11' }}
          />
        </group>
        <group
          name="headlight_21_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_21_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_21"
            geometry={nodes.headlight_21.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_21' }}
          />
        </group>
        <group
          name="headlight_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_01"
            geometry={nodes.headlight_01.geometry}
            material={materials.black}
            userData={{ name: 'headlight_01' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_18_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_18_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_18"
            geometry={nodes.headlight_18.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_18' }}
          />
        </group>
        <group
          name="headlight_22_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_22_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_22"
            geometry={nodes.headlight_22.geometry}
            material={materials.black}
            userData={{ name: 'headlight_22' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_08_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_08"
            geometry={nodes.headlight_08.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_08' }}
          />
        </group>
        <group
          name="headlight_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_07"
            geometry={nodes.headlight_07.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_07' }}
          />
        </group>
        <group
          name="headlight_14_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_14_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_14"
            geometry={nodes.headlight_14.geometry}
            material={materials.black}
            userData={{ name: 'headlight_14' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_09_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_09"
            geometry={nodes.headlight_09.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_09' }}
          />
        </group>
        <group
          name="headlight_17_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_17_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_17"
            geometry={nodes.headlight_17.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_17' }}
          />
        </group>
        <group
          name="headlight_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_06"
            geometry={nodes.headlight_06.geometry}
            material={materials.black}
            userData={{ name: 'headlight_06' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_20_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_20_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_20"
            geometry={nodes.headlight_20.geometry}
            material={materials.black}
            userData={{ name: 'headlight_20' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_23_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_23_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_23"
            geometry={nodes.headlight_23.geometry}
            material={materials.chrome}
            userData={{ name: 'headlight_23' }}
          />
        </group>
        <group
          name="headlight_12_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_12_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_12"
            geometry={nodes.headlight_12.geometry}
            material={materials.blue}
            userData={{ name: 'headlight_12' }}
          />
        </group>
        <group
          name="headlight_24_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_24_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_24"
            geometry={nodes.headlight_24.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_24' }}
          />
        </group>
        <group
          name="headlight_25_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_25_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_25"
            geometry={nodes.headlight_25.geometry}
            material={materials.black}
            userData={{ name: 'headlight_25' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="headlight_26_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'headlight_26_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="headlight_26"
            geometry={nodes.headlight_26.geometry}
            material={materials.clearglass}
            userData={{ name: 'headlight_26' }}
          />
        </group>
        <group
          name="Body_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_07_$AssimpFbx$_Translation' }}
        >
          {/* 车前方，引擎盖旁边 */}
          <mesh
            name="Body_07"
            geometry={nodes.Body_07.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_07' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="Body_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_08_$AssimpFbx$_Translation' }}
        >
          {/* 车门下方 */}
          <mesh
            name="Body_08"
            geometry={nodes.Body_08.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_08' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_02"
            geometry={nodes.windows_part_02.geometry}
            material={materials.black}
            userData={{ name: 'windows_part_02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_09_$AssimpFbx$_Translation' }}
        >
          {/* 车门 */}
          <mesh
            name="Body_09"
            geometry={nodes.Body_09.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_09' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_04"
            geometry={nodes.windows_part_04.geometry}
            material={materials.black}
            userData={{ name: 'windows_part_04' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_10_$AssimpFbx$_Translation' }}
        >
          {/* 车后玻璃上方 */}
          <mesh
            name="Body_10"
            geometry={nodes.Body_10.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_10' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="Body_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_11_$AssimpFbx$_Translation' }}
        >
          {/* 车侧边 门旁边 */}
          <mesh
            name="Body_11"
            geometry={nodes.Body_11.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_11' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="black_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'black_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="black_00"
            geometry={nodes.black_00.geometry}
            material={materials.black}
            userData={{ name: 'black_00' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="roof_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'roof_$AssimpFbx$_Translation' }}
        >
          <mesh name="roof" geometry={nodes.roof.geometry} material={materials.black} userData={{ name: 'roof' }}>
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_12_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_12_$AssimpFbx$_Translation' }}
        >
          {/* 车顶盖 */}
          <mesh
            name="Body_12"
            geometry={nodes.Body_12.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_12' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_01"
            geometry={nodes.windows_part_01.geometry}
            material={materials.darkglass}
            userData={{ name: 'windows_part_01' }}
          />
        </group>
        <group
          name="windows_part_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_05"
            geometry={nodes.windows_part_05.geometry}
            material={materials.black}
            userData={{ name: 'windows_part_05' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="interior_part_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'interior_part_01_$AssimpFbx$_Translation' }}
        >
          {/* 座椅加镜子方向盘 */}
          <mesh
            name="interior_part_01"
            geometry={nodes.interior_part_01.geometry}
            material={materials.interior}
            userData={{ name: 'interior_part_01' }}
          >
            <meshStandardMaterial {...seatMaterial} />
            {/* <meshPhysicalMaterial {...seatMaterial} /> */}
          </mesh>
        </group>
        <group
          name="windows_part_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_09_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_09"
            geometry={nodes.windows_part_09.geometry}
            material={materials.windowglass}
            userData={{ name: 'windows_part_09' }}
          />
        </group>
        <group
          name="bumper_part_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bumper_part_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bumper_part_00"
            geometry={nodes.bumper_part_00.geometry}
            material={materials.black}
            userData={{ name: 'bumper_part_00' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_13_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_13_$AssimpFbx$_Translation' }}
        >
          {/* 车屁股 */}
          <mesh
            name="Body_13"
            geometry={nodes.Body_13.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_13' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="black_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'black_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="black_02"
            geometry={nodes.black_02.geometry}
            material={materials.black}
            userData={{ name: 'black_02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="bumper_part_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bumper_part_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bumper_part_02"
            geometry={nodes.bumper_part_02.geometry}
            material={materials.mattemetal}
            userData={{ name: 'bumper_part_02' }}
          >
            <meshStandardMaterial {...matMaterial} />
          </mesh>
        </group>
        <group
          name="bottom02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bottom02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bottom02"
            geometry={nodes.bottom02.geometry}
            material={materials.black}
            userData={{ name: 'bottom02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="redglass01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'redglass01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="redglass01"
            geometry={nodes.redglass01.geometry}
            material={materials.redglass}
            userData={{ name: 'redglass01' }}
          >
            <meshStandardMaterial {...redLight} />
          </mesh>
        </group>
        <group
          name="Body_14_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_14_$AssimpFbx$_Translation' }}
        >
          {/* 车屁股 凹进去 */}
          <mesh
            name="Body_14"
            geometry={nodes.Body_14.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_14' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="interior_part_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'interior_part_00_$AssimpFbx$_Translation' }}
        >
          {/* 内壁 */}
          <mesh
            name="interior_part_00"
            geometry={nodes.interior_part_00.geometry}
            material={materials.interior}
            userData={{ name: 'interior_part_00' }}
          >
            <meshStandardMaterial {...floorMaterial} />
          </mesh>
        </group>
        <group
          name="interior_part_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'interior_part_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="interior_part_04"
            geometry={nodes.interior_part_04.geometry}
            material={materials.black}
            userData={{ name: 'interior_part_04' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_03"
            geometry={nodes.windows_part_03.geometry}
            material={materials.black}
            userData={{ name: 'windows_part_03' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_11_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_11"
            geometry={nodes.windows_part_11.geometry}
            material={materials.windowglass}
            userData={{ name: 'windows_part_11' }}
          />
        </group>
        <group
          name="interior_part_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'interior_part_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="interior_part_02"
            geometry={nodes.interior_part_02.geometry}
            material={materials.mirror}
            userData={{ name: 'interior_part_02' }}
          >
            <meshStandardMaterial {...mirrorMaterial} />
          </mesh>
        </group>
        <group
          name="gablight_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_03"
            geometry={nodes.gablight_03.geometry}
            material={materials.redglass}
            userData={{ name: 'gablight_03' }}
          >
            <meshStandardMaterial {...redLight} />
          </mesh>
        </group>
        <group
          name="gablight_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_04"
            geometry={nodes.gablight_04.geometry}
            material={materials.clearglass}
            userData={{ name: 'gablight_04' }}
          />
        </group>
        <group
          name="gablight_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_05"
            geometry={nodes.gablight_05.geometry}
            material={materials.clearglass}
            userData={{ name: 'gablight_05' }}
          />
        </group>
        <group
          name="gablight_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_06"
            geometry={nodes.gablight_06.geometry}
            material={materials.chrome}
            userData={{ name: 'gablight_06' }}
          />
        </group>
        <group
          name="gablight_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_07"
            geometry={nodes.gablight_07.geometry}
            material={materials.clearglass}
            userData={{ name: 'gablight_07' }}
          />
        </group>
        <group
          name="gablight_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'gablight_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="gablight_01"
            geometry={nodes.gablight_01.geometry}
            material={materials.clearglass}
            userData={{ name: 'gablight_01' }}
          />
        </group>
        <group
          name="face_part_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'face_part_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="face_part_07"
            geometry={nodes.face_part_07.geometry}
            material={materials.black}
            userData={{ name: 'face_part_07' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="Body_15_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'Body_15_$AssimpFbx$_Translation' }}
        >
          {/* 车屁股两个钉子 */}
          <mesh
            name="Body_15"
            geometry={nodes.Body_15.geometry}
            material={materials.carpaint}
            userData={{ name: 'Body_15' }}
          >
            <meshStandardMaterial {...bodyMaterial} />
          </mesh>
        </group>
        <group
          name="black_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'black_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="black_01"
            geometry={nodes.black_01.geometry}
            material={materials.black}
            userData={{ name: 'black_01' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="bumper_part_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'bumper_part_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="bumper_part_04"
            geometry={nodes.bumper_part_04.geometry}
            material={materials.black}
            userData={{ name: 'bumper_part_04' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_10_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_10"
            geometry={nodes.windows_part_10.geometry}
            material={materials.black}
            userData={{ name: 'windows_part_10' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="windows_part_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_08_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_08"
            geometry={nodes.windows_part_08.geometry}
            material={materials.chrome}
            userData={{ name: 'windows_part_08' }}
          />
        </group>
        <group
          name="windows_part_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'windows_part_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="windows_part_06"
            geometry={nodes.windows_part_06.geometry}
            material={materials.redglass}
            userData={{ name: 'windows_part_06' }}
          >
            <meshStandardMaterial {...redLight} />
          </mesh>
        </group>
        <group
          name="dvornik_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'dvornik_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="dvornik_02"
            geometry={nodes.dvornik_02.geometry}
            material={materials.black}
            userData={{ name: 'dvornik_02' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="dvornik_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'dvornik_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="dvornik_01"
            geometry={nodes.dvornik_01.geometry}
            material={materials.black}
            userData={{ name: 'dvornik_01' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="trunk_rubber_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'trunk_rubber_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="trunk_rubber"
            geometry={nodes.trunk_rubber.geometry}
            material={materials.black}
            userData={{ name: 'trunk_rubber' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>

        <group
          name="wh_fl_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_03"
            geometry={nodes.wh_fl_03.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_03' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_08_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_08"
            geometry={nodes.wh_fr_08.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_08' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_01"
            geometry={nodes.wh_fl_01.geometry}
            material={materials.brakedisk}
            userData={{ name: 'wh_fl_01' }}
          />
        </group>
        <group
          name="wh_fr_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_09_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_09"
            geometry={nodes.wh_fr_09.geometry}
            material={materials.brakedisk}
            userData={{ name: 'wh_fr_09' }}
          />
        </group>
        <group
          name="wh_fl_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_00"
            geometry={nodes.wh_fl_00.geometry}
            material={materials.tire}
            userData={{ name: 'wh_fl_00' }}
          >
            <meshPhysicalMaterial {...wheelMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_00_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_00_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_00"
            geometry={nodes.wh_fr_00.geometry}
            material={materials.tire}
            userData={{ name: 'wh_fr_00' }}
          >
            <meshPhysicalMaterial {...wheelMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_12_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_12_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_12"
            geometry={nodes.wh_fl_12.geometry}
            material={materials.white}
            userData={{ name: 'wh_fl_12' }}
          />
        </group>
        <group
          name="wh_fr_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_11_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_11"
            geometry={nodes.wh_fr_11.geometry}
            material={materials.rim_second}
            userData={{ name: 'wh_fr_11' }}
          />
        </group>
        <group
          name="wh_fl_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_02"
            geometry={nodes.wh_fl_02.geometry}
            material={materials.rim_second}
            userData={{ name: 'wh_fl_02' }}
          />
        </group>
        <group
          name="wh_fl_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_04"
            geometry={nodes.wh_fl_04.geometry}
            material={materials.rim}
            userData={{ name: 'wh_fl_04' }}
          />
        </group>
        <group
          name="wh_fl_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_05"
            geometry={nodes.wh_fl_05.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fl_05' }}
          />
        </group>
        <group
          name="wh_fl_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_06"
            geometry={nodes.wh_fl_06.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_06' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_07"
            geometry={nodes.wh_fl_07.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fl_07' }}
          />
        </group>
        <group
          name="wh_fl_08_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_08_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_08"
            geometry={nodes.wh_fl_08.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_08' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_09_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_09_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_09"
            geometry={nodes.wh_fl_09.geometry}
            material={materials.blue}
            userData={{ name: 'wh_fl_09' }}
          />
        </group>
        <group
          name="wh_fl_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_10_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_10"
            geometry={nodes.wh_fl_10.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_10' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_11_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_11_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_11"
            geometry={nodes.wh_fl_11.geometry}
            material={materials.white}
            userData={{ name: 'wh_fl_11' }}
          />
        </group>
        <group
          name="wh_fr_12_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_12_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_12"
            geometry={nodes.wh_fr_12.geometry}
            material={materials.rim}
            userData={{ name: 'wh_fr_12' }}
          />
        </group>
        <group
          name="wh_fr_01_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_01_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_01"
            geometry={nodes.wh_fr_01.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_01' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_02_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_02_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_02"
            geometry={nodes.wh_fr_02.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fr_02' }}
          />
        </group>
        <group
          name="wh_fr_03_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_03_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_03"
            geometry={nodes.wh_fr_03.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fr_03' }}
          />
        </group>
        <group
          name="wh_fr_04_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_04_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_04"
            geometry={nodes.wh_fr_04.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_04' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_05_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_05_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_05"
            geometry={nodes.wh_fr_05.geometry}
            material={materials.white}
            userData={{ name: 'wh_fr_05' }}
          />
        </group>
        <group
          name="wh_fr_06_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_06_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_06"
            geometry={nodes.wh_fr_06.geometry}
            material={materials.blue}
            userData={{ name: 'wh_fr_06' }}
          />
        </group>
        <group
          name="wh_fr_07_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_07_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_07"
            geometry={nodes.wh_fr_07.geometry}
            material={materials.white}
            userData={{ name: 'wh_fr_07' }}
          />
        </group>
        <group
          name="wh_fr_10_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_10_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_10"
            geometry={nodes.wh_fr_10.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_10' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_13_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_13_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_13"
            geometry={nodes.wh_fl_13.geometry}
            material={materials.brakedisk}
            userData={{ name: 'wh_fl_13' }}
          />
        </group>
        <group
          name="wh_fr_13_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_13_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_13"
            geometry={nodes.wh_fr_13.geometry}
            material={materials.brakedisk}
            userData={{ name: 'wh_fr_13' }}
          />
        </group>
        <group
          name="wh_fl_14_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_14_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_14"
            geometry={nodes.wh_fl_14.geometry}
            material={materials.tire}
            userData={{ name: 'wh_fl_14' }}
          >
            <meshPhysicalMaterial {...wheelMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_14_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_14_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_14"
            geometry={nodes.wh_fr_14.geometry}
            material={materials.tire}
            userData={{ name: 'wh_fr_14' }}
          >
            <meshPhysicalMaterial {...wheelMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_15_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_15_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_15"
            geometry={nodes.wh_fl_15.geometry}
            material={materials.white}
            userData={{ name: 'wh_fl_15' }}
          />
        </group>
        <group
          name="wh_fr_15_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_15_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_15"
            geometry={nodes.wh_fr_15.geometry}
            material={materials.rim_second}
            userData={{ name: 'wh_fr_15' }}
          />
        </group>
        <group
          name="wh_fl_16_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_16_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_16"
            geometry={nodes.wh_fl_16.geometry}
            material={materials.rim_second}
            userData={{ name: 'wh_fl_16' }}
          />
        </group>
        <group
          name="wh_fl_17_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_17_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_17"
            geometry={nodes.wh_fl_17.geometry}
            material={materials.rim}
            userData={{ name: 'wh_fl_17' }}
          />
        </group>
        <group
          name="wh_fl_18_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_18_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_18"
            geometry={nodes.wh_fl_18.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fl_18' }}
          />
        </group>
        <group
          name="wh_fl_19_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_19_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_19"
            geometry={nodes.wh_fl_19.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_19' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_20_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_20_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_20"
            geometry={nodes.wh_fl_20.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fl_20' }}
          />
        </group>
        <group
          name="wh_fl_21_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_21_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_21"
            geometry={nodes.wh_fl_21.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_21' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_22_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_22_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_22"
            geometry={nodes.wh_fl_22.geometry}
            material={materials.blue}
            userData={{ name: 'wh_fl_22' }}
          />
        </group>
        <group
          name="wh_fl_23_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_23_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_23"
            geometry={nodes.wh_fl_23.geometry}
            material={materials.black}
            userData={{ name: 'wh_fl_23' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fl_24_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fl_24_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fl_24"
            geometry={nodes.wh_fl_24.geometry}
            material={materials.white}
            userData={{ name: 'wh_fl_24' }}
          />
        </group>
        <group
          name="wh_fr_16_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_16_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_16"
            geometry={nodes.wh_fr_16.geometry}
            material={materials.rim}
            userData={{ name: 'wh_fr_16' }}
          />
        </group>
        <group
          name="wh_fr_17_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_17_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_17"
            geometry={nodes.wh_fr_17.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_17' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_18_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_18_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_18"
            geometry={nodes.wh_fr_18.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fr_18' }}
          />
        </group>
        <group
          name="wh_fr_19_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_19_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_19"
            geometry={nodes.wh_fr_19.geometry}
            material={materials.chrome}
            userData={{ name: 'wh_fr_19' }}
          />
        </group>
        <group
          name="wh_fr_20_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_20_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_20"
            geometry={nodes.wh_fr_20.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_20' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
        <group
          name="wh_fr_21_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_21_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_21"
            geometry={nodes.wh_fr_21.geometry}
            material={materials.white}
            userData={{ name: 'wh_fr_21' }}
          />
        </group>
        <group
          name="wh_fr_22_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_22_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_22"
            geometry={nodes.wh_fr_22.geometry}
            material={materials.blue}
            userData={{ name: 'wh_fr_22' }}
          />
        </group>
        <group
          name="wh_fr_23_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_23_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_23"
            geometry={nodes.wh_fr_23.geometry}
            material={materials.white}
            userData={{ name: 'wh_fr_23' }}
          />
        </group>
        <group
          name="wh_fr_24_$AssimpFbx$_Translation"
          position={[0, -108.62, 52]}
          userData={{ name: 'wh_fr_24_$AssimpFbx$_Translation' }}
        >
          <mesh
            name="wh_fr_24"
            geometry={nodes.wh_fr_24.geometry}
            material={materials.black}
            userData={{ name: 'wh_fr_24' }}
          >
            <meshStandardMaterial {...blackMaterial} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload(glbModel, dracoPath);
